# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://EdwardJRoss.github.io/webrefine_recipes/"

git_url = "https://github.com/EdwardJRoss/webrefine_recipes/tree/master/"

def custom_doc_links(name): return None
